### ISSUE TITLE
Webpack 4.16.5

### ISSUE THREAD

**Issue by branfordwang** [jhnns/rewire-webpack#27]
This is currently failing at compiler.parser.plugin because compiler.parser is undefined

   compiler.parser.plugin("var rewire", function () {
        return true;
    });

Browser console error:

TypeError: Cannot read property 'plugin' of undefined
    at RewirePlugin.apply (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/rewire-webpack/lib/RewirePlugin.js:22:21)
    at webpack (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/webpack/lib/webpack.js:47:13)
    at Plugin (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/karma-webpack/lib/karma-webpack.js:87:16)
    at invoke (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:75:15)
    at Array.instantiate (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:59:20)
    at get (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:48:43)
    at /Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:71:14
    at Array.map (<anonymous>)
    at Array.invoke (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:70:31)
    at Injector.get (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:48:43)
    at instantiatePreprocessor (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/karma/lib/preprocessor.js:55:20)
    at Array.forEach (<anonymous>)
    at createPreprocessor (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/karma/lib/preprocessor.js:74:20)
    at Array.invoke (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:75:15)
    at get (/Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:48:43)
    at /Users/bwang/Documents/workspace/ResponsiveBooking/node_modules/di/lib/injector.js:71:14

**Comment by rensbaardman** [comment]
Unfortunately, the plugin doesn't have webpack 4 support. Webpack 4 introduced a different plugin API, which you are seeing the errors of.

A solution is to use [my fork](https://github.com/rensbaardman/rewire-webpack-plugin) which supports webpack 4.
